### ISSUE TITLE
When re-starting grid-control it's unable to copy the tarball

### ISSUE THREAD

**Issue by rfriese** [grid-control/grid-control#5]
Hi,

i'm testing the new rc (just checked out). When I directly submit jobs with a fresh config file, some jobs succeed (9/10 failed, I don't know yet, why).

When I stop gc and re-start it, it searches for e.g

file:///nfs/dust/cms/user/rfriese/htautau/artus/2016-04-13_15-14_analysis/output/GC638e6ff91c6c.tar.gz

while the tarball for this job is called GCfdb6ea648351.tar.gz

Cheers,
Raphael

**Comment by FredStober** [comment]
problem was introduced in 5e9618e7a5beba06f47d77a0b8956d18f9747900
fixed by commit 2ebada510e33bbe4bfdc45390de845a3653d3e41
