### ISSUE TITLE
Inline commentar need blank before ;

### ISSUE THREAD

**Issue by garbersc** [grid-control/grid-control#62]
i.e.
TT_TuneCUETP8M2T4_mtop1665_13TeV_powheg_pythia8   => 0.051786743 ; 18962382, x-sec = 982
does work
but
TT_TuneCUETP8M2T4_mtop1665_13TeV_powheg_pythia8   => 0.051786743; 18962382, x-sec = 982
does not

**Comment by garbersc** [comment]
the problem seems to  be more complicated...

**Comment by garbersc** [comment]
the real code was
 ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1 => 0.005409526 ; 1000000, x-sec = 3.36 ; neg.weights factor 1.
it looks like the second semicolon is the problem

**Comment by jolange** [comment]
For the record:
The problem was a second ";" in the comment: everything to the right of the *last* ";" is treated as a comment. Everything before is included in the parameter value.
