### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by jolange** [grid-control/grid-control#68]
We should make it compatible with python3.7 soon. (Use the [python37](/grid-control/grid-control/tree/python37) branch.)

The testsuite fails at the moment. At least one breaking change is [PEP 479 -- Change StopIteration handling inside generators](https://www.python.org/dev/peps/pep-0479).

**Comment by mseidel42** [comment]
Hi Johannes,

lxplus7 will be phased out soon (2024-06-27) and lxplus9 has python3.9 by default.

Would it be possible to make grid-control compatible with that so that it can be used in the following years?

Best,
Markus

**Comment by jolange** [comment]
@mseidel42 progress is slow, but there is some...
It's still not ported to python 3.9. You can follow the progress on #86

If you have python 3.7 available, you can already test your configs, because there's still some chance that I did not catch problems in the CMS-related code parts (see #88).

**Comment by mseidel42** [comment]
Hi Johannes, thanks a lot! We got an interim solution using python2.7 from miniforge, we can update that to 3.7 then :+1:

Let me just put it here for reference if anybody stumbles upon this, I assume it should just work the same for 3.7 (to be checked)
```sh
# Get and install miniforge
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
# Note: do NOT let the installer activate it by default
bash Miniforge3-Linux-x86_64.sh
# Activate miniforge
source ~/miniforge3/etc/profile.d/conda.sh
# Create python2.7 environment
conda create -n cf2.7 python=2.7
# Activate python2.7  environment
conda activate cf2.7
```

**Comment by jolange** [comment]
Thanks! Maybe we can take that offline, but why do you use a 2.7 environment instead of 3.6?

Another suggestion for people who don't want to switch to a completely different ecosystem just for running grid-control:
I personally use [pyenv](https://github.com/pyenv/pyenv) to use different python versions.

**Comment by mseidel42** [comment]
Python 2.7 was what worked on lxplus7 before :D

Pyenv looks interesting also, does it work on lxplus?

**Comment by jolange** [comment]
Ah, I see :D Python 3.6 should have also worked all the time.

I never used it on lxplus, but it should work. It basically runs everywhere where python compiles, which has very little dependencies. This can restrict the python versions that will work, e.g. due to old system SSL versions that are no longer supported (Python >=3.10 will not compile on EL7 without manually updating SSL).
